name: i18nify-react Release

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      # - name: Publish to github registry
      #   id: changesets
      #   uses: changesets/action@v1
      #   if: github.event_name != 'workflow_dispatch' # only run on master merges
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      #   with:
      #     publish: yarn release
      #     commit: 'build(i18nify-react): update version'
      #     title: 'build(i18nify-react): update version'
      - name: Publish to GitHub Package Registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}
