name: i18nify-react Release

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: |
          echo "@tarun-khanna:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_TOKEN }}" >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}
